export const allProducts = [
    { brand: 'HP', model: 'HP 840 G7', processor: 'I5', gen: '10TH', memory: '8GB', storage: '256GB', qty: 1 },
    { brand: 'HP', model: 'HP 840 G7', processor: 'I5', gen: '10TH', memory: '8GB', storage: '256GB', qty: 37 },
    { brand: 'HP', model: 'HP 840 G6', processor: 'I7', gen: '8TH', memory: '8GB', storage: '256GB', qty: 1 },
    { brand: 'HP', model: 'HP 440 G6', processor: 'I7', gen: '8TH', memory: '8GB', storage: '256GB', qty: 2 },
    { brand: 'HP', model: 'HP 450 G6', processor: 'I5', gen: '8TH', memory: '8GB', storage: '256GB', qty: 1 },
    { brand: 'HP', model: 'HP 840 G3', processor: 'I7', gen: '6TH', memory: '8GB', storage: '256GB', qty: 1 },
    { brand: 'HP', model: 'HP ZBOOK 14', processor: 'I5', gen: '4TH', memory: '4GB', storage: '500GB', qty: 1 },
    { brand: 'DELL', model: 'DELL 7400 2 IN 1', processor: 'I5', gen: '8TH', memory: '8GB', storage: '256GB', qty: 1 },
    { brand: 'DELL', model: 'DELL 5290 2IN1', processor: 'I5', gen: '8TH', memory: '8GB', storage: '256GB', qty: 2 },
    { brand: 'DELL', model: 'DELL 3390 2 IN 1', processor: 'I5', gen: '8TH', memory: '8GB', storage: '256GB', qty: 4 },
    { brand: 'DELL', model: 'DELL 3310 2 IN 1', processor: 'I5', gen: '8TH', memory: '8GB', storage: '256GB', qty: 1 },
    { brand: 'DELL', model: 'DELL 7285 2IN1', processor: 'I5', gen: '7TH', memory: '8GB', storage: '256GB', qty: 2 },
    { brand: 'DELL', model: 'DELL 5280 2IN1', processor: 'I5', gen: '7TH', memory: '8GB', storage: '256GB', qty: 1 },
    { brand: 'DELL', model: 'DELL 5490', processor: 'I5', gen: '8TH', memory: '8GB', storage: '256GB', qty: 6 },
    { brand: 'DELL', model: 'DELL 7390', processor: 'I5', gen: '8TH', memory: '8GB', storage: '256GB', qty: 2 },
    { brand: 'DELL', model: 'DELL 5300', processor: 'I5', gen: '8TH', memory: '8GB', storage: '256GB', qty: 8 },
    { brand: 'DELL', model: 'DELL 3400', processor: 'I5', gen: '8TH', memory: '8GB', storage: '256GB', qty: 7 },
    { brand: 'DELL', model: 'DELL 3530', processor: 'I5', gen: '8TH', memory: '8GB', storage: '256GB', qty: 1 },
    { brand: 'DELL', model: 'DELL 5480', processor: 'I5', gen: '7TH', memory: '8GB', storage: '256GB', qty: 3 },
    { brand: 'DELL', model: 'DELL 3380', processor: 'I5', gen: '7TH', memory: '8GB', storage: '256GB', qty: 1 },
    { brand: 'DELL', model: 'DELL 7470', processor: 'I7', gen: '6TH', memory: '8GB', storage: '256GB', qty: 1 },
    { brand: 'DELL', model: 'DELL 5480', processor: 'I5', gen: '6TH', memory: '8GB', storage: '256GB', qty: 9 },
    { brand: 'DELL', model: 'DELL 7440', processor: 'I5', gen: '4TH', memory: '4GB', storage: '500GB', qty: 3 },
    { brand: 'DELL', model: 'DELL 7420', processor: 'I5', gen: '4TH', memory: '4GB', storage: '500GB', qty: 1 },
    { brand: 'DELL', model: 'DELL E6440', processor: 'I5', gen: '4TH', memory: '4GB', storage: '500GB', qty: 1 },
    { brand: 'LENOVO', model: 'LENOVO P50', processor: 'XEON', gen: 'E3', memory: '8GB', storage: '256GB', qty: 2 },
    { brand: 'LENOVO', model: 'LENOVO YOGA C740', processor: 'I5', gen: '10TH', memory: '8GB', storage: '256GB', qty: 6 },
    { brand: 'LENOVO', model: 'LENOVO X390 YOGA', processor: 'I7', gen: '8TH', memory: '8GB', storage: '256GB', qty: 2 },
    { brand: 'LENOVO', model: 'LENOVO P52', processor: 'I7', gen: '8TH', memory: '8GB', storage: '256GB', qty: 2 },
    { brand: 'LENOVO', model: 'LENOVO T480S', processor: 'I5', gen: '8TH', memory: '8GB', storage: '256GB', qty: 5 },
    { brand: 'LENOVO', model: 'LENOVO YOGA L380/L390', processor: 'I5', gen: '8TH', memory: '8GB', storage: '256GB', qty: 5 },
    { brand: 'LENOVO', model: 'LENOVO T490', processor: 'I5', gen: '8TH', memory: '8GB', storage: '256GB', qty: 1 },
    { brand: 'LENOVO', model: 'LENOVO X280 TOUCH', processor: 'I5', gen: '8TH', memory: '8GB', storage: '256GB', qty: 2 },
    { brand: 'LENOVO', model: 'LENOVO L480', processor: 'I5', gen: '8TH', memory: '8GB', storage: '256GB', qty: 1 },
    { brand: 'LENOVO', model: 'LENOVO L580', processor: 'I5', gen: '8TH', memory: '8GB', storage: '256GB', qty: 4 },
    { brand: 'LENOVO', model: 'LENOVO L370 2IN1', processor: 'I5', gen: '7TH', memory: '8GB', storage: '256GB', qty: 1 },
    { brand: 'LENOVO', model: 'LENOVO T470', processor: 'I5', gen: '7TH', memory: '8GB', storage: '256GB', qty: 3 },
    { brand: 'LENOVO', model: 'LENOVO X270', processor: 'I5', gen: '7TH', memory: '8GB', storage: '256GB', qty: 4 },
    { brand: 'LENOVO', model: 'LENOVO E570', processor: 'I5', gen: '7TH', memory: '8GB', storage: '256GB', qty: 3 },
    { brand: 'LENOVO', model: 'LENOVO X270', processor: 'I5', gen: '7TH', memory: '8GB', storage: '256GB', qty: 3 },
    { brand: 'LENOVO', model: 'LENOVO T470', processor: 'I5', gen: '6TH', memory: '8GB', storage: '256GB', qty: 1 },
    { brand: 'LENOVO', model: 'LENOVO E560', processor: 'I5', gen: '6TH', memory: '8GB', storage: '256GB', qty: 1 },
    { brand: 'LENOVO', model: 'LENOVO X260', processor: 'I5', gen: '6TH', memory: '8GB', storage: '256GB', qty: 2 },
    { brand: 'LENOVO', model: 'LENOVO T460S', processor: 'I5', gen: '6TH', memory: '8GB', storage: '256GB', qty: 1 },
    { brand: 'LENOVO', model: 'LENOVO X250', processor: 'I5', gen: '5TH', memory: '4GB', storage: '500GB', qty: 3 },
    { brand: 'LENOVO', model: 'LENOVO T450', processor: 'I5', gen: '5TH', memory: '4GB', storage: '500GB', qty: 1 },
    { brand: 'LENOVO', model: 'LENOVO T550', processor: 'I5', gen: '5TH', memory: '4GB', storage: '500GB', qty: 1 },
    { brand: 'LENOVO', model: 'LENOVO YOGA 12', processor: 'I5', gen: '4TH', memory: '4GB', storage: '500GB', qty: 5 },
    { brand: 'LENOVO', model: 'LENOVO T440P', processor: 'I5', gen: '4TH', memory: '4GB', storage: '500GB', qty: 1 },
    { brand: 'MIX BRAND', model: 'TOSHIBA Z30-C', processor: 'I5', gen: '6TH', memory: '8GB', storage: '256GB', qty: 1 },
    { brand: 'MIX BRAND', model: 'MIX 6TH TO 10TH GEN', processor: 'MIX', gen: 'MIX', memory: '8GB', storage: '256GB', qty: 11 },
    { brand: 'MIX BRAND', model: 'MIX 2ND TO 5TH GEN', processor: 'MIX', gen: 'MIX', memory: '4GB', storage: '500GB', qty: 49 },
    { brand: 'MIX BRAND', model: 'FUJITSU', processor: 'MIX', gen: '4TH', memory: '5GB', storage: '500GB', qty: 5 }
];
